# local configuration
services:
  server:
    build:
      context: .
      target: local
    image: alexp327/pediatric-pain-rater:local
    ports:
      - 4200:4200
    volumes:
      - .:/app
# production configuration
# services:
#   server:
#     build:
#       context: .
#       target: prod
#     image: alexp327/pediatric-pain-rater:prod
#     ports:
#       - 8080:80
